---
title: "Analysis of CRC Spatial Transcriptomics data from 10X: Ligand-Receptor Interactions"
author: 'Alberto Valdeolivas Urbelz (PS-Biomics&Path)'
date: '`r format(Sys.time(), "%d %B, %Y")`'
output:
  html_document:
    code_folding: hide
    self_contained: true
    number_sections: yes
    toc: true
    toc_depth: 2
    toc_float:
      collapsed: false
      smooth_scroll: false
    theme: spacelab
  pdf_document:
    number_sections: yes
    toc: yes
    toc_depth: 3
params:
  data_directory : "/pstore/data/biomics/_pre_portfolio/_platform_evaluation/SpatialTranscriptomics/Experiment_CRC_AllSamples/"
  analysis_name : "analysis_alberto/"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

```{r, warning=FALSE, message=FALSE}
library(dplyr, lib.loc = "/pstore/apps/bioinfo/R/4.0.1-foss")
library(patchwork, lib.loc = "/pstore/home/valdeola/R/x86_64-pc-linux-gnu-library/4.0.1-foss")
library(Seurat, lib.loc = "/pstore/apps/bioinfo/R/4.0.1-foss")
library(tibble, lib.loc = "/pstore/apps/bioinfo/R/4.0.1-foss")
library(readr, lib.loc = "/pstore/apps/bioinfo/R/4.0.1-foss")
library(stringr, lib.loc = "/pstore/apps/bioinfo/R/4.0.1-foss")
library(ggplot2, lib.loc = "/pstore/apps/bioinfo/R/4.0.1-foss")
library(cowplot, lib.loc = "/pstore/apps/bioinfo/R/4.0.1-foss")
library(RColorBrewer, lib.loc = "/pstore/apps/bioinfo/R/4.0.1-foss")
library(liana,  lib.loc = "/pstore/apps/bioinfo/R/4.0.1-foss")

source(file = "WrapperFunction/SeuratWrappers.R")
source(file = "WrapperFunction/PseudoBulkUtils.R")

data_directory <-  params$data_directory
analysis_name <- params$analysis_name

input_files <- "IntermediaryFiles/MergeClustering/"
input_names <- "SeuratObject_dorothea_res05.rds"

files_to_read <- paste0(data_directory, analysis_name,input_files,input_names)
results_directory <- paste0(data_directory, analysis_name, input_files)
```

Reading Seurat objects

```{r warning=FALSE, message=FALSE}
seurat_objects_markers <- readRDS(files_to_read)
Seurat_merge_object <- seurat_objects_markers[[2]]
DefaultAssay(Seurat_merge_object) <- "SCT"
```

Running LIANA 

```{r, warning=FALSE, message=FALSE}
liana_results <- liana_wrap(Seurat_merge_object) %>% 
  liana_aggregate()
```


Plotting results for our top ligands. 

```{r, warning=FALSE, message=FALSE}
my_ligands <- c("CXCL14", "LUM", "THBS2", "RNF43","PLAU", "DCN", "MMP1")

liana_significan_myligands <- liana_results %>% 
  dplyr::filter(ligand %in% my_ligands) %>%
  dplyr::filter(source %in% c("1", "0"), target %in% c("1")) %>% 
  dplyr::filter(aggregate_rank < 0.01) 

liana_significan_myligands %>%
  # top_n(25, desc(aggregate_rank)) %>%
  liana_dotplot(source_groups = c("0", "1"),
                target_groups = c("1"))
```

```{r, warning=FALSE,message=FALSE, eval=TRUE}
filename_lianaResults <- 
  paste0(data_directory, analysis_name, input_files, 
      "lianaResults.rds")

saveRDS(liana_results, file = filename_lianaResults)
```


# Session Info Details

```{r, echo=FALSE, eval=TRUE}
sessionInfo()
```

